### ISSUE TITLE
Docker Images and Formation Expansion

### ISSUE THREAD

**Issue by ekristen** [cholcombe973/autodock#2]
Any plan to allow for someone to just specific a docker image they want to run instead of building via a salt formula?

Can you scale a formation up or down?

**Comment by cholcombe973** [comment]
Yup I do have plans to run an image without salt.  I haven't gotten around to it yet.  Pull requests are more than welcome :)

It does have support for scaling the formation up but not down yet.  Would you like to create a formation deletion command?

**Comment by ekristen** [comment]
I just found this tool so I am looking into it more. 

Good to know the the scaling up function is there, deletion and scale down would be awesome too. 

Thanks for the tool!
